 @startuml
'https://plantuml.com/class-diagram
allowmixing

class DataStorage {
- dbConnection: Connection
+ add(): void
+ update()
+ delete()
+ get()
}

class PatientData {

- patientId: String
- metrics: List<Metric>
- timestamp: long
+ getPatientId(): int
+ getMetrics(): List<Metric>
+ getTimestamp(): long

}

class Metric {

 - name: String
 - value: double
 + getName(): String
 + getValue(): double

}

class DataRetriever {

- authenticatedUser: User
+ add(): void
+ update()
+ delete()
+ get(): PatientData

}

class User {

- userId: int
- username: String
- password: String
- isActive: boolean
+ User()

}

class UserPermission {

- userId: int
- patientId: String
- isReadOnly: boolean
- validFrom: date
- expiredAt: date

}


DataRetriever --> UserPermission: uses
DataRetriever --> User: uses
DataRetriever --> PatientData: uses
DataRetriever --> DataStorage: calls
DataStorage --> PatientData: uses
UserPermission --> User: uses
PatientData --> Metric: uses

package "com.cardiogenerator.generators"
@enduml